package com.quicktap.data.entity;
// Generated Feb 28, 2016 1:13:33 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChartsQuestions generated by hbm2java
 */
@Entity
@Table(name = "charts_questions")
public class ChartsQuestions implements java.io.Serializable {

	private Integer id;
	private Charts charts;
	private QuestionTypes questionTypes;

	public ChartsQuestions() {
	}

	public ChartsQuestions(Charts charts, QuestionTypes questionTypes) {
		this.charts = charts;
		this.questionTypes = questionTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "charts_id", nullable = false)
	public Charts getCharts() {
		return this.charts;
	}

	public void setCharts(Charts charts) {
		this.charts = charts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "questions_id", nullable = false)
	public QuestionTypes getQuestionTypes() {
		return this.questionTypes;
	}

	public void setQuestionTypes(QuestionTypes questionTypes) {
		this.questionTypes = questionTypes;
	}

}
