package com.quicktap.data.entity;
// Generated Feb 16, 2016 9:48:34 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions", catalog = "mydb")
public class Questions implements java.io.Serializable {

	private int id;
	private Surveys surveys;
	private long questionNo;
	private String title;
	private Set<Responses> responseses = new HashSet<Responses>(0);

	public Questions() {
	}

	public Questions(int id, Surveys surveys, long questionNo, String title) {
		this.id = id;
		this.surveys = surveys;
		this.questionNo = questionNo;
		this.title = title;
	}

	public Questions(int id, Surveys surveys, long questionNo, String title, Set<Responses> responseses) {
		this.id = id;
		this.surveys = surveys;
		this.questionNo = questionNo;
		this.title = title;
		this.responseses = responseses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "surveys_id", nullable = false)
	public Surveys getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Surveys surveys) {
		this.surveys = surveys;
	}

	@Column(name = "question_no", nullable = false)
	public long getQuestionNo() {
		return this.questionNo;
	}

	public void setQuestionNo(long questionNo) {
		this.questionNo = questionNo;
	}

	@Column(name = "title", nullable = false, length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
	public Set<Responses> getResponseses() {
		return this.responseses;
	}

	public void setResponseses(Set<Responses> responseses) {
		this.responseses = responseses;
	}

}
