package com.quicktap.data.entity;
// Generated Feb 20, 2016 7:10:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResponseValues generated by hbm2java
 */
@Entity
@Table(name = "response_values")
public class ResponseValues implements java.io.Serializable {

	private Integer id;
	private Questions questions;
	private Responses responses;
	private String value;

	public ResponseValues() {
	}

	public ResponseValues(Questions questions, Responses responses) {
		this.questions = questions;
		this.responses = responses;
	}

	public ResponseValues(Questions questions, Responses responses, String value) {
		this.questions = questions;
		this.responses = responses;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade={CascadeType.REMOVE,CascadeType.PERSIST})
	@JoinColumn(name = "questions_id", nullable = false)
	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responses_id", nullable = false)
	public Responses getResponses() {
		return this.responses;
	}

	public void setResponses(Responses responses) {
		this.responses = responses;
	}

	@Column(name = "value", length = 500)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
