package com.quicktap.data.entity;
// Generated Feb 17, 2016 2:34:22 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResponseValues generated by hbm2java
 */
@Entity
@Table(name = "response_values", catalog = "mydb")
public class ResponseValues implements java.io.Serializable {

	private int id;
	private Responses responses;
	private String value;

	public ResponseValues() {
	}

	public ResponseValues(int id, Responses responses, String value) {
		this.id = id;
		this.responses = responses;
		this.value = value;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responses_id", nullable = false)
	public Responses getResponses() {
		return this.responses;
	}

	public void setResponses(Responses responses) {
		this.responses = responses;
	}

	@Column(name = "value", nullable = false, length = 500)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
