package com.quicktap.data.entity;
// Generated Mar 14, 2016 8:30:04 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Responses generated by hbm2java
 */
@Entity
@Table(name = "responses")
public class Responses implements java.io.Serializable {

	private Integer id;
	private Surveys surveys;
	private String dateCollected;
	private String dateSent;
	private String userName;
	private Float latitude;
	private Float longitude;
	private Set<ResponseValues> responseValueses = new HashSet<ResponseValues>(0);

	public Responses() {
	}

	public Responses(Surveys surveys, String dateCollected, String dateSent, String userName) {
		this.surveys = surveys;
		this.dateCollected = dateCollected;
		this.dateSent = dateSent;
		this.userName = userName;
	}

	public Responses(Surveys surveys, String dateCollected, String dateSent, String userName, Float latitude,
			Float longitude, Set<ResponseValues> responseValueses) {
		this.surveys = surveys;
		this.dateCollected = dateCollected;
		this.dateSent = dateSent;
		this.userName = userName;
		this.latitude = latitude;
		this.longitude = longitude;
		this.responseValueses = responseValueses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "surveys_id", nullable = false)
	public Surveys getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Surveys surveys) {
		this.surveys = surveys;
	}

	@Column(name = "date_collected", nullable = false, length = 45)
	public String getDateCollected() {
		return this.dateCollected;
	}

	public void setDateCollected(String dateCollected) {
		this.dateCollected = dateCollected;
	}

	@Column(name = "date_sent", nullable = false, length = 45)
	public String getDateSent() {
		return this.dateSent;
	}

	public void setDateSent(String dateSent) {
		this.dateSent = dateSent;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "latitude", precision = 10, scale = 6)
	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 10, scale = 6)
	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "responses")
	public Set<ResponseValues> getResponseValueses() {
		return this.responseValueses;
	}

	public void setResponseValueses(Set<ResponseValues> responseValueses) {
		this.responseValueses = responseValueses;
	}

}