package com.quicktap.data.entity;
// Generated Feb 17, 2016 1:35:46 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Responses generated by hbm2java
 */
@Entity
@Table(name = "responses", catalog = "mydb")
public class Responses implements java.io.Serializable {

	private Integer id;
	private Questions questions;
	private Users users;
	private String dateCollected;
	private String dateSent;
	private Set<ResponseValues> responseValueses = new HashSet<ResponseValues>(0);

	public Responses() {
	}

	public Responses(Questions questions, Users users, String dateCollected, String dateSent) {
		this.questions = questions;
		this.users = users;
		this.dateCollected = dateCollected;
		this.dateSent = dateSent;
	}

	public Responses(Questions questions, Users users, String dateCollected, String dateSent,
			Set<ResponseValues> responseValueses) {
		this.questions = questions;
		this.users = users;
		this.dateCollected = dateCollected;
		this.dateSent = dateSent;
		this.responseValueses = responseValueses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "questions_id", nullable = false)
	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "date_collected", nullable = false, length = 45)
	public String getDateCollected() {
		return this.dateCollected;
	}

	public void setDateCollected(String dateCollected) {
		this.dateCollected = dateCollected;
	}

	@Column(name = "date_sent", nullable = false, length = 45)
	public String getDateSent() {
		return this.dateSent;
	}

	public void setDateSent(String dateSent) {
		this.dateSent = dateSent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responses")
	public Set<ResponseValues> getResponseValueses() {
		return this.responseValueses;
	}

	public void setResponseValueses(Set<ResponseValues> responseValueses) {
		this.responseValueses = responseValueses;
	}

}
