package com.quicktap.data.entity;
// Generated Feb 16, 2016 9:48:34 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SurveyUserLinks generated by hbm2java
 */
@Entity
@Table(name = "survey_user_links", catalog = "mydb")
public class SurveyUserLinks implements java.io.Serializable {

	private int id;
	private Surveys surveys;
	private Users users;

	public SurveyUserLinks() {
	}

	public SurveyUserLinks(int id, Surveys surveys, Users users) {
		this.id = id;
		this.surveys = surveys;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "surveys_id", nullable = false)
	public Surveys getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Surveys surveys) {
		this.surveys = surveys;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
